Repository OrderN/CONQUEST-release, pull requests merged in 2023-08, with the labels that each got.

#235 Add documentation on energy, forces and stresses
  docs/index.rst
  docs/references.bib
  docs/theory_energy_force_stress.rst
Labels: area: manual

#216 PP: Add Fermi_offset
  tools/PostProcessing/stm_module.f90
Labels: area: utilities, improves: functionality, priority: minor, time: hours, type: bug

#239 Update system.make
  src/system.make
  tools/BasisGeneration/system.make
Labels: area: main-source, priority: minor, time: hours, type: maintenance

#195 Thread loops over blocks
  .github/workflows/makefile.yml
  docs/installing.rst
  src/.gitignore
  src/PAO_grid_transform_module.f90
  src/calc_matrix_elements_module.f90
  src/functions_on_grid_module.f90
  src/gha.make
  src/initial_read_module.f90
  src/main.f90
  src/odd.obj
  src/omp_module.f90
  src/omp_moduleDUMMY.f90
  src/system.make
  testsuite/run_conquest_tests.sh
Labels: area: main-source, improves: speed, time: days, type: enhancement
