Repository OrderN/CONQUEST-release, pull requests merged in 2023-07, with the labels that each got.

#204 Improve LFD range input
  src/initial_read_module.f90
Labels: area: main-source, improves: stability, priority: major, time: hours, type: bug

#201 Refactor the testsuite
  testsuite/README.md
  testsuite/test_check_output.py
Labels: area: testing, improves: output, time: hours, type: maintenance, project: eCSE8

#207 Add selecting custom precision by key
  testsuite/README.md
  testsuite/test_check_output.py
Labels: area: testing, time: hours, type: enhancement

#212 Tidied defaults for band densities
  tools/PostProcessing/process_module.f90
  tools/PostProcessing/read_module.f90
Labels: area: utilities

#218 Fixed problems with non-SCF forces and structural optimisation
  src/force_module.f90
  src/move_atoms.module.f90
Labels: area: main-source, priority: major, time: hours, type: bug

#225 Pull request for f-proj_PadHamiltonianMatrix
  src/ScalapackFormat.f90
Labels: area: main-source, improves: functionality, priority: major, time: days, type: enhancement

#227 Pull request to proj_PadHamiltonianMatrix (should work with a given block size)
  src/DiagModule.f90
  src/ScalapackFormat.f90
Labels: area: main-source, improves: functionality, needs: review, priority: major, time: days, type: enhancement

#229 Fix non-NA and non-SCF stress issues
  docs/input_tags.rst
  src/XC_CQ_module.f90
  src/XC_LibXC_v4_module.f90
  src/XC_LibXC_v5_module.f90
  src/force_module.f90
  src/initial_read_module.f90
Labels: area: main-source, improves: stability, priority: minor, type: bug
