Repository OrderN/CONQUEST-release, pull requests merged in 2024-02, with the labels that each got.

#318 Add extended XYZ file output for static run and structural optimization
  src/control.f90
  src/initial_read_module.f90
Labels: area: main-source, improves: functionality, needs: review

#328 Correct array references and allocation in LibXC modules
  src/XC_LibXC_v4_module.f90
  src/XC_LibXC_v5_module.f90
Labels: area: main-source, improves: stability, priority: major, time: hours, type: bug

#323 276 use blas
  src/exx_kernel_default.f90
  src/exx_memory.f90
  src/exx_types.f90
Labels: improves: speed

#324 276 thread exx phi on grid
  src/exx_evalpao.f90
  src/ol_ang_coeff_subs.f90
Labels: improves: speed

#333 Updates to fix RTD and add information on restarting
  .readthedocs.yml
  docs/groundstate.rst
  docs/input_tags.rst
  docs/installing.rst
Labels: area: manual, priority: minor, time: hours, type: release

#335 Changed default system.make behaviour, tidied up files
  docs/installing.rst
  src/Makefile
  src/system/system.example.make
  src/system/system.gha.make
  src/system/system.kathleen.make
  src/system/system.young.make
Labels: area: main-source, priority: minor, time: hours, type: maintenance
